// REGISTER 
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "1234"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "validation@example.com",
  "password": "1234"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "@example.com",
  "password": "1234"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "validation@example.com",
  "password": "123"
}

###
// LOGIN
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "mail@example.com", 
  "password": "1234"
}

###
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "mail@example.com", 
  "password": "wrong"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "validation@example.com"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "password": "1234"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "@example.com",
  "password": "1234"
}

// GET ME
### 
GET http://localhost:3001/api/auth/me
Content-Type: application/json
Authorization: bearer <TOKEN>

// UPDATE ME
### 
PUT http://localhost:3001/api/auth/me
Content-Type: application/json
Authorization: bearer <TOKEN>

{
  "name": "sup User",
  "bio": "I'm the super user",
  "location": "Hell, Norway"
}

### 
PUT http://localhost:3001/api/auth/me
Content-Type: application/json
Authorization: bearer <TOKEN>

{
  "name": "SUPER USER"
}

### 
PUT http://localhost:3001/api/auth/me
Content-Type: application/json
Authorization: bearer <TOKEN>

{
  "bio": "this is bio",
  "location": ""
}

