// Create tweets
POST http://localhost:3001/api/tweets
Content-Type: application/json
Authorization: bearer <TOKEN>

{
  "content": "first tweet from backend"
}

###
// Like tweets
PUT http://localhost:3001/api/tweets/:id/like
Content-Type: application/json
Authorization: bearer <TOKEN>

{
}

###
// Tweet replies
GET http://localhost:3001/api/tweets/61607f2a5039068dc8eb561f/replies
Content-Type: application/json

{
}